language: c

os: osx

osx_image: xcode9.2

compiler: gcc

before_install:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - cmake --build . --config Debug --target all
  - ./tests
